name: my first workflow


on: push

jobs:
    first_jobs:
        runs_on: ubuntu-latest
        steps:
            - name: welcome message
              runs: echo "welcome to github actions"
            - name: list files
              runs: ls