name: my first workflow

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v6
      
      - name: welcome message
        run: echo "welcome to github actions"

      # Step 3: List files in the repository
      - name: list files
        run: ls
        