name: ascii artwork 

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - name: list repo files
        run : ls -ltra
      
      - name: execute shell script
        run: |
          
            chmod +x .github/workflows/asciiscript.sh
            bash .github/workflows/asciiscript.sh
     

            
        