name:  jobs 

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
       - name: building file
         run:  echo "i am trying to get my first job in companies." > job.txt   
       - uses: actions/upload-artifact@v4
         with:
           name: job-text-file
           path: job.txt
  test_job:
    needs: [build_job]
    runs-on: ubuntu-latest
    steps:
       - uses: actions/download-artifact@v4
         with:
           name: job-text-file
           
       - name: testing file
         run: grep "job" job.txt 
  deploy_job:
    needs: [test_job]
    runs-on: ubuntu-latest
    steps:
       - uses: actions/download-artifact@v4
         with:
           name: job-text-file
           
       - name: display content
         run: cat job.txt
       
        
            
        