name: ascii artwork 

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - name: list repo files
        run : ls -ltra
      
      - name: welcome message and list files
        run: |
          
            chmod +x asciiscript.sh
            ./asciiscript.sh
     

            
        