name: matrix configuration
on:
    push

jobs:
    deploy:
       strategy:
        fail-fast: false
        
        matrix:
         os: [ubuntu-latest, ubuntu-20.04, windows-latest]
         images: [ hello-world, alpine]
         exclude:
            - images: alpine
              os: windows-latest
       runs-on: ${{ matrix.os }}
       steps:
         - name: docker details
           run: docker info
         - name: run image on ${{ matrix.os }}
           run: docker run ${{ matrix.images }}


         
