name: run ci
on: [ push, pull_request ]

jobs:
    normal-ci:
        runs-on: ubuntu-latest
        steps:
         - name: Run normal ci
           run: echo "running normal ci"
    pull-request-ci:
         runs-on: ubuntu-latest
         if: ${{ github.event_name == 'push' }}
         steps:
         - name: Run pr ci
           run: echo "running pr only ci"
              